In [1]:
from Player import Player
from Trainer import Trainer
from TetrisModel import TetrisModel
from Pretrainer import Pretrainer
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import glob
import time

In [2]:
piece_dim = 8
key_dim = 12
depth = 16
gamma = 0.99
lam = 0.95

In [3]:
# Use lambda instead of gamma to immitate shape of gae without value predictions
pretrainer = Pretrainer(gamma=lam)

In [4]:
players_data = pretrainer._load_data()

In [5]:
pretrainer._load_dset(players_data)

0.08


KeyboardInterrupt



In [3]:
# max_len = pretrainer._max_len
max_len = 7

In [9]:
gt_dset = pretrainer._cache_dset()

Done Caching


In [4]:
agent = TetrisModel(piece_dim=piece_dim,
                    key_dim=key_dim,
                    depth=depth,
                    num_heads=4,
                    num_layers=4,
                    max_length=max_len)

In [5]:
logits, values = agent((tf.random.uniform((1, 28, 10, 1)),
                        tf.random.uniform((1, 7), minval=0, maxval=8, dtype=tf.int32),
                        tf.random.uniform((1, max_len-1), minval=0, maxval=key_dim, dtype=tf.int32)))
agent.summary(), tf.shape(logits), tf.shape(values)

Model: "tetris_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential (Sequential)     (1, 70, 16)               4800      
                                                                 
 seq_embedding (SeqEmbedding  multiple                 128       
 )                                                               
                                                                 
 seq_embedding_1 (SeqEmbeddi  multiple                 192       
 ng)                                                             
                                                                 
 pdec_0 (DecoderLayer)       multiple                  9776      
                                                                 
 pdec_1 (DecoderLayer)       multiple                  9776      
                                                                 
 pdec_2 (DecoderLayer)       multiple                 

(None,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1,  6, 12])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 6, 1])>)

In [6]:
agent_optimizer = keras.optimizers.Adam(learning_rate=1e-6)
agent.compile(optimizer=agent_optimizer)

In [7]:
ref_agent = TetrisModel(piece_dim=piece_dim,
                        key_dim=key_dim,
                        depth=depth,
                        num_heads=4,
                        num_layers=4,
                        max_length=max_len)

In [8]:
logits, values = agent((tf.random.uniform((1, 28, 10, 1)),
                        tf.random.uniform((1, 7), minval=0, maxval=8, dtype=tf.int32),
                        tf.random.uniform((1, max_len-1), minval=0, maxval=key_dim, dtype=tf.int32)))

In [9]:
agent.load_weights('agent_weights/agent_finetuned')

In [10]:
ref_agent.load_weights('agent_weights/agent_finetuned')

In [11]:
epochs = 10

In [ ]:
losses, accs = pretrainer.train(agent, gt_dset, epochs)

In [ ]:
plt.plot(losses)
plt.plot(accs)

In [15]:
if 'y' in input('YOU SURE?????'):
    agent.save_weights('agent_weights/agent_finetuned')

YOU SURE????? y


In [11]:
%matplotlib qt

In [12]:
optimizers = keras.optimizers.Adam(learning_rate=1e-6), keras.optimizers.Adam(learning_rate=1e-6)

In [16]:
trainer = Trainer(model=agent,
                  ref_model=ref_agent,
                  optimizers=optimizers,
                  max_len=max_len,
                  gamma=gamma,
                  lam=lam,
                  max_episode_steps=100,
                  buffer_cap=1000)

In [17]:
trainer.fill_replay_buffer()

Done filling replay buffer


In [ ]:
trainer.train(gens=10000, train_steps=10, training_actor=True)

Current Gen: 1	|	Avg Reward: 0.0	|	Total Reward: 7.1	|
Current Gen: 2	|	Avg Reward: 0.0	|	Total Reward: 7.4	|9	|	
Current Gen: 3	|	Avg Reward: 0.0	|	Total Reward: 5.5	|4	|	
Current Gen: 4	|	Avg Reward: 0.0	|	Total Reward: 9.8	|5	|	
Current Gen: 5	|	Avg Reward: 0.0	|	Total Reward: 7.5	|6	|	
Current Gen: 6	|	Avg Reward: 0.0	|	Total Reward: 13.7	|	|	
Current Gen: 7	|	Avg Reward: 0.0	|	Total Reward: 13.0	|	|	
Current Gen: 8	|	Avg Reward: 0.0	|	Total Reward: 13.2	|	|	
Current Gen: 9	|	Avg Reward: 0.0	|	Total Reward: 7.0	|0	|	
Current Gen: 10	|	Avg Reward: 0.0	|	Total Reward: 7.8	|	|	
Current Gen: 11	|	Avg Reward: 0.0	|	Total Reward: 3.7	|	|	
Current Gen: 12	|	Avg Reward: 0.0	|	Total Reward: 8.8	|	|	
Current Gen: 13	|	Avg Reward: 0.0	|	Total Reward: 3.5	|	|	
Current Gen: 14	|	Avg Reward: 0.0	|	Total Reward: 10.8	||	
Current Gen: 15	|	Avg Reward: 0.0	|	Total Reward: 11.6	||	
Current Gen: 16	|	Avg Reward: 0.0	|	Total Reward: 6.5	|	|	
Current Gen: 17	|	Avg Reward: 0.0	|	Total Reward: 8.3	|	|	
C

In [23]:
episode_data = trainer.player.run_episode(agent, max_steps=1000, greedy=True, renderer=trainer.renderer)

In [24]:
episode_boards, episode_pieces, episode_inputs, episode_actions, episode_valid, episode_probs, episode_values, episode_rewards = episode_data

In [25]:
episode_advantages, episode_returns = trainer._compute_gae(episode_values, episode_rewards, trainer.gamma, trainer.lam)

In [26]:
fig, ax = plt.subplots()
ax.plot(episode_returns, label='Returns')
ax.plot(episode_rewards, label='Rewards')
ax.plot(episode_values, label='Values')
ax.plot(episode_advantages, label='Advantages')
ax.legend()
tf.reduce_sum(episode_rewards)

<tf.Tensor: shape=(), dtype=float32, numpy=25.850002>